### ISSUE TITLE
More detailed inline blame

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#126]
There should be possibility to display more details in editor inlined blame.

**Comment by aaronols** [comment]
I like the inline blame as it was released in 183.3.0 👍 .

What I would like to see added to this extensions is the option to display the commit date relative to the current date aswell as the first line of the commit message.
A screenshot from the gitlens extension showing how they implemented this can be found here for reference: https://raw.githubusercontent.com/eamodio/vscode-gitlens/master/images/docs/current-line-blame.png

**Comment by aaronols** [comment]
While we're at it, I also like subtle dark grey color of the inline blame that gitlens uses. It is nicer on the eyes than the bright grey used at the moment when using the Darcula theme.
Could you make the inline blame color configurable or choosable from preset colors?

**Comment by zielu** [comment]
@aaronols all colors can be adjusted in `Settings > Editor > Color Scheme > Git ToolBox `

**Comment by zielu** [comment]
Darcula color adjustment to be done in #127

**Comment by zielu** [comment]
@aaronols beta version is released to eap channel. It still has one issue when status bar and inline blames are enabled together but I should finish it next week.
Global setting have new Blame tab that contains configuration options.

**Comment by aaronols** [comment]
Just updated to 191.0.3 and so far I love it. Have not run into any bugs.

I would suggest renaming the `Show subject` option to `Show first line of commit message` for clarity.

There is no noticeable slowdown for me when opening files that are in a git repository. The blame is displayed as soon as it is ready (Thumbs up for non-blocking loading in the background).
I checked the JMX stats to see what impact the blame loading has on my machine.
The `blame-cache-load` Timer has a mean value of 900ms.

I have disabled the status bar blame since all information is now readily available in the inline blame.

**Comment by zielu** [comment]
Finished in 191.0.4

**Comment by amarjeet** [comment]
@zielu After an upgrade to IntelliJ Idea Ultimate 2019.1 and updating the plugin, whenever editor context switches to a new file, IDE freezes for a few seconds with the message "Computing annotation for <file_name_opened>". This happens only for tracked files. Just FYI.

**Comment by zielu** [comment]
@amarjeet improvements implementation is tracked under #139
