### ISSUE TITLE
DataGrip support

### ISSUE THREAD

**Issue by oleksii-vynnychenko** [zielu/GitToolBox#132]
Basically title says it all - it's not available in DataGrip and it would be very nice to have that. For example I'm storing all SQL scripts in git.

p.s. It's very helpful plugin and I'm using it all other IJ IDEs, thank you for your work :)

**Comment by zielu** [comment]
Hi, I'll look into this, I thought I had all products covered :/
You are on 2018 ?

**Comment by oleksii-vynnychenko** [comment]
Currently on 2019.1 EAP

![image](https://user-images.githubusercontent.com/20228387/54266038-43131d00-457f-11e9-80f9-faf6cc6c5d67.png)

Thing is, I used GitToolBox in first half of 2018, it was supporting DataGrip, but then maybe starting from autumn 2018 it no longer does...

**Comment by zielu** [comment]
It's not possible right now - seems that because my plugin declares dependency on bundled Git plugin it marks DataGrip as not compatible. 
![image](https://user-images.githubusercontent.com/464103/54311999-1ccc9c00-45d6-11e9-84d0-b09d2fa79828.png)
There is a workaround though: In DG you have to install Git Integration and later download my plugin and install it manually.

**Comment by zielu** [comment]
Submitted question on Jetbrains forums: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003317920-DataGrip-Git4Idea-plugin-dependency

**Comment by oleksii-vynnychenko** [comment]
Oh, indeed, I had JB git plugin already, so just installed from disk and it's now in DG. Thanks a lot.

It's indeed weird then to say on JB plugin repository site that it's not compatible with DG when in fact it is.

Anyway, thank you for your time and explanation.

**Comment by zielu** [comment]
Hi, Jetbrains fixed DataGrip compatibility info on their side or is should be available normally now.
