### ISSUE TITLE
The newest IDEA version can not use GitToolBox

### ISSUE THREAD

**Issue by ThounderStruck** [zielu/GitToolBox#188]
As the title，GitToolBox can not compatible for the newest IDEA( March 2019),Please resolve as soon as possible，thank you!

**Comment by zielu** [comment]
@ThounderStruck newest idea 2019.3 was released on 28 Nov and it's supported. If you tried installing latest release on plugin in anything older then it won't work and is by design to reduce  maintenance.
Could you add more details which exact plugin version and idea release are you trying to marry together ?

**Comment by zielu** [comment]
I sometimes do a backport one version back but it depends on the effort. So for example backport to 2019.2 is not out of the question but there will not be one to 2019.1 almost for sure.

**Comment by littleneko** [comment]
update the plugin to 193.2.1, it's ok

**Comment by zielu** [comment]
Major part of version number matches supported intellij release.

**Comment by ThounderStruck** [comment]
I uninstall first and then reinstall,the problem has been resolved.thank you!

**Comment by ThounderStruck** [comment]
I uninstall first and then reinstall,the problem has been resolved.thank you!
