### ISSUE TITLE
Inline blame doesn't work when server is running

### ISSUE THREAD

**Issue by lexelpro** [zielu/GitToolBox#229]
Hello. I've noticed that when the tomcat server is running then inline blame isn't showing anymore.
When server is not running inline blame is there
![Screenshot1](https://i.imgur.com/A9vO70X.png)
When server is running inline blame is not there
![Screenshot2](https://i.imgur.com/l2MBDGy.png)

IntelliJ IDEA 2019.3.4 (Ultimate Edition)
Build #IU-193.6911.18, built on March 17, 2020

GitTooblox v.193.7.2

**Comment by zielu** [comment]
Hi @lexelpro it's because you are in debug mode. 
This is a new feature that hides blame while debugging - reason for change was that in turn blame was hiding IDE `Show Values Inline` (#214)

You can make it visible again by unchecking Preferences > GitToolBox Global > Blame > Hide inline blame while debugging.

**Comment by zielu** [comment]
As a side note - it should not be hidden if you're not using `Show Values Inline`. I'll create task for this case

**Comment by lexelpro** [comment]
Ok, I didn't know it. It works when unchecking Preferences > GitToolBox Global > Blame > Hide inline blame while debugging. Thank you.
