### ISSUE TITLE
[Feature] Cleanup of old branches - more configuration

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#313]
TODO:
- [x] outdated branches selection mode [always, on demand]
- [x] confirm outdated branches selection

Split to separate tasks
- [x] #362
- [x] #361

**Comment by sekullbe** [comment]
Inactivity config, especially with a "never" option, would be lovely- I just had to restore a couple of unmerged branches from reflogs that got deleted by cleanup. I didn't carefully check the list because there were 3000 branches in it and I thought only merged and old branches would be deleted. I'd like to be able to only remove merged branches.

**Comment by zielu** [comment]
@sekullbe I'll add option for outdated branches that only make only merged ones selected by default and maybe additional confirmation dialog to removal if you have any outdated selected.

Actually plugin is recording removal history (branch name + commit it was pointing at) but just stores it. Looks like it's the moment to actually implement rollback functionality on top of that.
