### ISSUE TITLE
Feature request: Auto-Fetch all remotes immediately when project is opened

### ISSUE THREAD

**Issue by theo-3** [zielu/GitToolBox#317]

**Comment by zielu** [comment]
Hi, first auto-fetch is executed after a delay that is dependant on number of repositories, but no less than 10 sec.
Formula for duration in seconds is `Math.round(Math.max(10, Math.log(reposCount) * 6 + 1))`

**Comment by theo-3** [comment]
Hi! Sorry, I just tested it with a private repo and it does fetch when opened. My main branch was tracking my fork instead of the upstream.

**Comment by theo-3** [comment]
Why isn't the first auto-fetch executed as soon as it can be though? The delay is a bit confusing.

**Comment by zielu** [comment]
There was an issue in the past about slow IDE start that was directly related to fetching too soon, but it makes sense to decrease min time. It will improve single repo situation.

**Comment by theo-3** [comment]
Maybe add an option in the settings menu to disable the delay with an explanation of the slow start problem. Shouldn't the plugin only start doing stuff after the IDE has been initialized though? Or was the IDE not opening until all the repos were fetched

**Comment by zielu** [comment]
IDE initialisation is a tricky thing because lots of things are happening concurrently and even after opening project progress bar. I created #321 and will just remove minimum 10 seconds delay. Users with significant amount of repositories won't be affected because for them calculated delay will be higher than 10 sec anyway.
