### ISSUE TITLE
Git Extender integration

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#43]
When Git Extender is also installed provide option to select which action should be invoked when 'Update project' is clicked in notification popup.

When option is for Git Extender is selected but plugin is not installed/disabled - reset to default.

id = gr.jchrist.gitextender

**Comment by zielu** [comment]
Done in 171.2.0

**Comment by achekulaev** [comment]
Hello!

Is there a way to include an item(s) "Git Stat" popup menu, so that Update and/or Git Extender could be invoked from there?

<img width="54" alt="menu" src="https://user-images.githubusercontent.com/402007/61493853-9d374b00-a982-11e9-881e-7361febfd524.png">


If you would consider it, I can create a fresh ticket.

Thanks in advance!

**Comment by zielu** [comment]
Hi, I will probably remove Git Extender support in the future. It was there only because it handled branches without remotes. Now that IntelliJ can do that I see no point in keeping it.

**Comment by zielu** [comment]
@achekulaev #157
