### ISSUE TITLE
[BUG] Auto-fetch resets Git history - cannot reproduce

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#530]
**Describe the bug**
I don't know how many times I'm inspecting GIT history and then POP - everything resets and I'm looking at latest head.
I found out today it was the Auto fetch feature screwing with me.

**To Reproduce**
This time, (and this happened to me MANY times) I was looking at a (1) file diff from a commit 2 years ago (2) git tool window scrolled to that commit - I clicked to open the (1) diff from said window

**Expected behavior**
N/A

**Plugin version**
500.1.8+222

**IDE version**
N/A

**Screenshots**

**Comment by zielu** [comment]
Cannot reproduce. Tested scenario:
1. open Git Log
2. select commit
3. git diff view
4. wait for auto-fetch to fetch new commit

Result:
- Log view is updated
- commit selection does not change
- diff view does not change

**Comment by raveren** [comment]
I tried and I cannot reproduce it either, just that time when I originally described - the `Autofetch finished` notification popped up at the same time as the views reset.

Since I don't actually know what caused this, I have removed the bad review from the plugin, am sorry for that and will keep an eye out to what's causing this...

Thank you for your hard and heartfelt work!!!

**Comment by zielu** [comment]
Hi, thanks you for removing the review. If you encounter any issues, have ideas to share, just reach out ! :)
